# Generated by Django 4.2.1 on 2023-09-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
