# Generated by Django 4.2.1 on 2023-09-23 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signup',
            new_name='signups',
        ),
    ]
