# Generated by Django 4.2.1 on 2023-11-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_clothdonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clothDonation',
        ),
    ]
