# Generated by Django 4.2.1 on 2023-09-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_rename_signup_signups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signups',
            new_name='signup',
        ),
    ]
