# Generated by Django 4.2.1 on 2023-09-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0005_rename_signups_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('current_role', models.CharField(choices=[('student', 'Student'), ('job', 'Full Time Job'), ('learner', 'Full Time Learner'), ('preferNo', 'Prefer not to say'), ('other', 'Other')], max_length=20)),
                ('internship_experience', models.CharField(choices=[('yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('why_choose_ngo', models.CharField(choices=[('Flexible Working Hours', 'Flexible Working Hours'), ('Certificates and Letter of Recommendation', 'Certificates and Letter of Recommendation'), ('Stipends', 'Stipends'), ('Social activities', 'Social activities')], max_length=50)),
                ('areas_of_interest', models.CharField(max_length=50)),
                ('additional_skills', models.TextField()),
            ],
        ),
    ]
