# Generated by Django 4.2.1 on 2023-09-26 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0006_internship'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Internship',
            new_name='intantship',
        ),
    ]
