# Generated by Django 4.2.1 on 2023-09-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0007_rename_internship_intantship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intantship',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
