# Generated by Django 4.2.1 on 2023-11-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0010_healthcamp_status_scholarshipapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmember',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=255),
        ),
    ]
