# Generated by Django 4.2.1 on 2023-10-04 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0010_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='intantship',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
    ]
