# Generated by Django 4.2.1 on 2023-11-18 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0011_newmember_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewMember',
        ),
    ]
