# Generated by Django 4.2.1 on 2023-10-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ngo', '0011_delete_intantship_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='intantship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('current_role', models.CharField(choices=[('student', 'Student'), ('job', 'Full Time Job'), ('learner', 'Full Time Learner'), ('preferNo', 'Prefer not to say'), ('other', 'Other')], max_length=20)),
                ('internship_experience', models.CharField(choices=[('yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('why_choose_ngo', models.CharField(choices=[('Flexible Working Hours', 'Flexible Working Hours'), ('Certificates and Letter of Recommendation', 'Certificates and Letter of Recommendation'), ('Stipends', 'Stipends'), ('Social activities', 'Social activities')], max_length=50)),
                ('areas_of_interest', models.CharField(max_length=50)),
                ('additional_skills', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('phonenumber', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('email', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(upload_to='Media/UserImage/%Y/')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
    ]
