# Generated by Django 4.2.1 on 2023-10-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0014_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='forwhom',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff')], max_length=5),
        ),
    ]
