# Generated by Django 4.2.1 on 2023-12-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0015_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='countrycode',
            new_name='phonecode',
        ),
    ]
