# Generated by Django 4.2.1 on 2023-10-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0015_alter_signup_forwhom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='forwhom',
            field=models.CharField(choices=[('u', 'User'), ('s', 'Staff')], max_length=1),
        ),
    ]
