# Generated by Django 4.2.1 on 2023-10-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0016_alter_signup_forwhom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='phonenumber',
            field=models.CharField(help_text='Format: +919876543210', max_length=13),
        ),
    ]
