# Generated by Django 4.2.1 on 2023-10-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0017_alter_signup_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('area_code', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('street_address', models.CharField(max_length=255)),
                ('street_address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=10)),
                ('type_of_donation', models.CharField(choices=[('Financial Donations', 'Financial Donations'), ('Clothing', 'Clothing'), ('Shoes and Bags', 'Shoes and Bags'), ('Kitchenware', 'Kitchenware'), ('Books', 'Books'), ('Toys and Games', 'Toys and Games'), ('Arts', 'Arts'), ('Linens', 'Linens'), ('Hygiene Essentials', 'Hygiene Essentials'), ('Sporting Goods', 'Sporting Goods'), ('Furniture', 'Furniture'), ('Other', 'Other')], max_length=255)),
                ('what_would_you_like_to_donate', models.TextField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
