# Generated by Django 4.2.1 on 2023-12-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0018_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthCamp',
        ),
        migrations.DeleteModel(
            name='ScholarshipApplication',
        ),
        migrations.DeleteModel(
            name='SocialEvent',
        ),
        migrations.DeleteModel(
            name='UserStory',
        ),
    ]
