# Generated by Django 4.2.1 on 2023-12-08 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0020_healthcamp_scholarshipapplication_socialevent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clothDonation',
        ),
        migrations.DeleteModel(
            name='FoodDonation',
        ),
    ]
