# Generated by Django 4.2.1 on 2023-10-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0021_rename_street_address_educationdonation_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationDonation',
        ),
    ]
