# Generated by Django 4.2.1 on 2023-12-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0022_clothdonation_fooddonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthCamp',
        ),
        migrations.DeleteModel(
            name='ScholarshipApplication',
        ),
        migrations.DeleteModel(
            name='SocialEvent',
        ),
        migrations.DeleteModel(
            name='UserStory',
        ),
    ]
