# Generated by Django 4.2.1 on 2023-12-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0024_healthcamp_scholarshipapplication_socialevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=255),
        ),
    ]
