# Generated by Django 4.2.1 on 2023-10-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0024_clothdonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationDonation',
        ),
    ]
