# Generated by Django 4.2.1 on 2023-12-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0025_signup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='forwhom',
            field=models.CharField(choices=[('user', 'User'), ('staff', 'Staff')], max_length=5),
        ),
        migrations.AlterField(
            model_name='signup',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6),
        ),
    ]
