# Generated by Django 4.2.1 on 2023-10-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0027_rename_phone_area_code_clothdonation_phone_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothdonation',
            old_name='notes',
            new_name='note',
        ),
    ]
