# Generated by Django 4.2.1 on 2023-12-10 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0028_remove_notification_staff_alter_notification_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
