# Generated by Django 4.2.1 on 2023-10-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0029_fooddonation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooddonation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='fooddonation',
            name='state',
        ),
    ]
