# Generated by Django 4.2.1 on 2023-12-10 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0031_alter_feedback_feedback_type_alter_feedback_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='image',
        ),
    ]
