# Generated by Django 4.2.1 on 2023-10-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0032_alter_fooddonation_time_needed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clothDonation',
        ),
        migrations.AlterField(
            model_name='socialevent',
            name='file_upload',
            field=models.FileField(upload_to='socialevent/'),
        ),
    ]
