# Generated by Django 4.2.1 on 2023-12-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0032_remove_feedback_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
