# Generated by Django 4.2.1 on 2023-10-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0034_clothdonation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothdonation',
            old_name='photo',
            new_name='image',
        ),
    ]
