# Generated by Django 4.2.1 on 2023-12-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0034_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffNotification',
        ),
    ]
