# Generated by Django 4.2.1 on 2023-10-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0035_rename_photo_clothdonation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialevent',
            name='activity_time',
            field=models.CharField(max_length=20),
        ),
    ]
