# Generated by Django 4.2.1 on 2023-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0036_alter_socialevent_activity_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcamp',
            name='dateday',
        ),
        migrations.RemoveField(
            model_name='healthcamp',
            name='datemonth',
        ),
        migrations.RemoveField(
            model_name='healthcamp',
            name='dateyear',
        ),
        migrations.AddField(
            model_name='healthcamp',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
