# Generated by Django 4.2.1 on 2023-10-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0037_remove_healthcamp_dateday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarshipapplication',
            old_name='dateday',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='datemonth',
        ),
        migrations.RemoveField(
            model_name='scholarshipapplication',
            name='dateyear',
        ),
    ]
