# Generated by Django 4.2.1 on 2023-12-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0037_rename_name_staffnotification_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffnotification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
