# Generated by Django 4.2.1 on 2023-10-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0039_moneydonation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoneyDonation',
        ),
    ]
