# Generated by Django 4.2.1 on 2023-10-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0040_delete_moneydonation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formType', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('ph_code', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('area_code', models.CharField(max_length=10)),
                ('donation_amount', models.IntegerField()),
                ('razorpay_order_id', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
