# Generated by Django 4.2.1 on 2023-11-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0044_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventImage',
        ),
    ]
