# Generated by Django 4.2.1 on 2023-11-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0046_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('compliment', 'Compliment'), ('suggestion', 'Suggestion'), ('thought', 'thought')], max_length=20),
        ),
    ]
