# Generated by Django 4.2.1 on 2023-11-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0048_newmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmember',
            name='image',
            field=models.ImageField(blank=True, upload_to='new_members/'),
        ),
        migrations.AlterField(
            model_name='newmember',
            name='member_type',
            field=models.CharField(max_length=50),
        ),
    ]
