# Generated by Django 4.2.1 on 2023-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0049_alter_newmember_image_alter_newmember_member_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_datetime', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
