# Generated by Django 4.2.1 on 2023-11-07 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0051_calendar_calendarevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clothDonation',
        ),
        migrations.DeleteModel(
            name='EducationDonation',
        ),
        migrations.DeleteModel(
            name='FoodDonation',
        ),
    ]
