# Generated by Django 4.2.1 on 2023-11-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0052_delete_clothdonation_delete_educationdonation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('condition', models.CharField(max_length=100)),
                ('type_of_dress', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='clothdonation_photos/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EducationDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formType', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('ph_code', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('area_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=255)),
                ('type_of_donation', models.CharField(choices=[('Financial Donations', 'Financial Donations'), ('Clothing', 'Clothing'), ('Shoes and Bags', 'Shoes and Bags'), ('Kitchenware', 'Kitchenware'), ('Books', 'Books'), ('Toys and Games', 'Toys and Games'), ('Arts', 'Arts'), ('Linens', 'Linens'), ('Hygiene Essentials', 'Hygiene Essentials'), ('Sporting Goods', 'Sporting Goods'), ('Furniture', 'Furniture'), ('Other', 'Other')], max_length=255)),
                ('what_would_you_like_to_donate', models.TextField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=20)),
                ('organization_name', models.CharField(max_length=255)),
                ('organization_mission', models.TextField()),
                ('date_needed', models.DateField()),
                ('time_needed', models.CharField(max_length=255)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_city', models.CharField(max_length=100)),
                ('pickup_state', models.CharField(max_length=100)),
                ('pickup_postal_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=255)),
            ],
        ),
    ]
