# Generated by Django 4.2.1 on 2023-11-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0053_clothdonation_educationdonation_fooddonation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmember',
            name='image',
            field=models.ImageField(upload_to='members/images/'),
        ),
    ]
