# Generated by Django 4.2.1 on 2023-11-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0054_alter_newmember_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmember',
            name='image',
            field=models.ImageField(blank=True, upload_to='new_members/'),
        ),
    ]
