# Generated by Django 4.2.1 on 2023-11-17 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0055_alter_newmember_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='dob',
        ),
    ]
