# Generated by Django 4.2.1 on 2023-11-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0056_remove_signup_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmember',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newmember',
            name='image',
            field=models.ImageField(upload_to='new_members/'),
        ),
    ]
