# Generated by Django 4.2.1 on 2023-11-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0057_alter_newmember_description_alter_newmember_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newmember',
            old_name='image',
            new_name='uploaded_file',
        ),
    ]
