# Generated by Django 4.2.1 on 2023-11-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0058_rename_image_newmember_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmember',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
